import type {
  Account,
  Conversation,
  ConversionDriver,
  DiagnosticDriver,
  RepPerformance,
} from "./types";

export const reps = [
  "Aarav Mehta",
  "Priya Nair",
  "Rohan Gupta",
  "Sara Williams",
  "Vikram Reddy",
];

/** Team-level conversion (win rate) this period vs last, derived for the demo. */
export const teamConversion = { current: 34, previous: 41 };

/**
 * The "why" behind the team conversion dip — behavioral drivers VoiceLog
 * extracted across every conversation, not numbers a CRM could ever capture.
 */
export const teamDiagnostics: DiagnosticDriver[] = [
  {
    label: "Pricing / financing discussed early",
    value: "38% of deals",
    delta: -12,
    impact: "negative",
    detail: "Reps are surfacing price late, after the objection has hardened.",
  },
  {
    label: "Competitor objections raised by buyers",
    value: "in 47% of calls",
    delta: 27,
    impact: "negative",
    detail: "Zoho & Patanjali credit-term mentions spiked vs last month.",
  },
  {
    label: "Discovery questions per conversation",
    value: "4.1 avg",
    delta: -24,
    impact: "negative",
    detail: "Less qualification up front correlates with lower win rate.",
  },
  {
    label: "Next step captured before call ends",
    value: "71% of calls",
    delta: -9,
    impact: "negative",
    detail: "Deals without a committed next step stall in pipeline.",
  },
];

/** Behaviors ranked by how strongly they correlate with closing. */
export const conversionDrivers: ConversionDriver[] = [
  { behavior: "Discusses pricing / financing early", correlation: 0.62 },
  { behavior: "Asks 3+ discovery questions", correlation: 0.55 },
  { behavior: "Captures a committed next step", correlation: 0.48 },
  { behavior: "Engages the economic buyer (not just champion)", correlation: 0.44 },
  { behavior: "Handles competitor objection on the call", correlation: 0.39 },
  { behavior: "Builds personal rapport (relationship score)", correlation: 0.31 },
];

export const repPerformance: RepPerformance[] = [
  {
    name: "Aarav Mehta",
    region: "Bengaluru",
    focus: "B2B SaaS",
    deals: 18,
    won: 9,
    winRate: 50,
    prevWinRate: 44,
    behaviors: { discoveryQs: 6.2, pricingEarly: 72, objectionHandled: 81, nextStepCaptured: 88 },
  },
  {
    name: "Sara Williams",
    region: "Austin",
    focus: "B2B SaaS",
    deals: 14,
    won: 6,
    winRate: 43,
    prevWinRate: 40,
    behaviors: { discoveryQs: 5.4, pricingEarly: 64, objectionHandled: 74, nextStepCaptured: 79 },
  },
  {
    name: "Vikram Reddy",
    region: "Kanpur / Nashik",
    focus: "Field Sales",
    deals: 22,
    won: 8,
    winRate: 36,
    prevWinRate: 47,
    behaviors: { discoveryQs: 4.0, pricingEarly: 41, objectionHandled: 62, nextStepCaptured: 70 },
  },
  {
    name: "Priya Nair",
    region: "Lucknow",
    focus: "Field Sales",
    deals: 16,
    won: 4,
    winRate: 25,
    prevWinRate: 38,
    behaviors: { discoveryQs: 3.1, pricingEarly: 29, objectionHandled: 55, nextStepCaptured: 61 },
  },
  {
    name: "Rohan Gupta",
    region: "Lucknow (exited)",
    focus: "Field Sales",
    deals: 11,
    won: 3,
    winRate: 27,
    prevWinRate: 33,
    behaviors: { discoveryQs: 3.6, pricingEarly: 38, objectionHandled: 58, nextStepCaptured: 64 },
  },
];

/** Top objections aggregated across all conversations (drives the "why"). */
export const objectionTrends = [
  { label: "Price / per-seat cost", count: 14, delta: 18 },
  { label: "Credit / payment terms", count: 11, delta: 22 },
  { label: "Competitor offering more", count: 9, delta: 27 },
  { label: "Internal approval / budget cycle", count: 7, delta: 4 },
  { label: "Security / compliance", count: 5, delta: -10 },
];

export const conversations: Conversation[] = [
  {
    id: "c1",
    accountId: "a1",
    title: "Pricing pushback + procurement loop",
    channel: "WhatsApp Call",
    language: "Hinglish",
    date: "2026-06-11T15:20:00",
    durationMin: 14,
    rep: "Aarav Mehta",
    transcript: [
      {
        speaker: "Aarav (Rep)",
        side: "rep",
        text: "Rahul ji, thanks for taking the call. Did you get a chance to look at the proposal I shared on WhatsApp?",
        t: 0,
      },
      {
        speaker: "Rahul Verma",
        side: "prospect",
        text: "Haan dekha, but honestly the per-seat pricing is on the higher side. Zoho is quoting us almost 30% less for similar features.",
        t: 12,
        drives: ["objections", "competitors", "pricingDiscussed"],
      },
      {
        speaker: "Aarav (Rep)",
        side: "rep",
        text: "Understood. The Zoho plan you're comparing doesn't include the call-intelligence add-on though. Can I show you a side-by-side?",
        t: 30,
      },
      {
        speaker: "Rahul Verma",
        side: "prospect",
        text: "Theek hai, but final call budget pe mera nahi hota. I'll have to take this to Anjali, our VP Sales — she signs off above 8 lakhs.",
        t: 45,
        drives: ["orgSignals", "bant.authority"],
      },
      {
        speaker: "Aarav (Rep)",
        side: "rep",
        text: "Got it. Would it help if I prepared a one-pager for Anjali focused on ROI rather than features?",
        t: 60,
      },
      {
        speaker: "Rahul Verma",
        side: "prospect",
        text: "Yes please. And waise bhi, we want to go live before our Q3 sales kickoff in August, so timeline is tight.",
        t: 72,
        drives: ["nextSteps", "bant.timeline"],
      },
      {
        speaker: "Aarav (Rep)",
        side: "rep",
        text: "Perfect, August works. I'll send the ROI one-pager by tomorrow and we can loop Anjali in next week. By the way, how was your daughter's admission — did the Bangalore school work out?",
        t: 88,
      },
      {
        speaker: "Rahul Verma",
        side: "prospect",
        text: "Arre haan, ho gaya! Thanks for remembering yaar. Bahut tension thi.",
        t: 102,
        drives: ["relationshipSignals", "sentiment"],
      },
    ],
    extracted: {
      stageSignal: "Negotiation",
      nextSteps: [
        "Send ROI-focused one-pager for VP Sales (Anjali) by tomorrow",
        "Schedule joint call with Anjali next week",
        "Align go-live before Q3 kickoff (August)",
      ],
      objections: ["Per-seat price perceived as 30% higher than Zoho"],
      competitors: ["Zoho CRM"],
      pricingDiscussed: "Per-seat plan, deal ceiling ₹8L requires VP approval",
      sentiment: "Mixed",
      bant: {
        budget: "Above ₹8L needs VP Sales sign-off",
        authority: "Rahul is champion, not economic buyer (Anjali = VP Sales)",
        need: "Wants call-intelligence + CRM in one; comparing vs Zoho",
        timeline: "Go-live before August Q3 kickoff",
      },
      orgSignals: [
        "Economic buyer identified: Anjali (VP Sales), approves >₹8L",
        "Rahul = champion / influencer, not final signer",
      ],
      relationshipSignals: [
        "Strong personal rapport — rep remembered daughter's school admission",
        "Prospect uses informal Hinglish + 'yaar' → comfortable relationship",
      ],
    },
    crmPush: {
      target: "Zoho",
      payload: {
        account: "Nexus Retail Cloud",
        dealStage: "Negotiation",
        nextActivity: {
          type: "Task",
          subject: "Send ROI one-pager for VP Sales",
          dueDate: "2026-06-12",
        },
        contactUpdate: {
          name: "Rahul Verma",
          role: "Champion",
          relationshipTemp: "Warm",
        },
        riskFlag: "Competitor: Zoho (price)",
        forecast: { closeBefore: "2026-08-01" },
      },
    },
  },
  {
    id: "c2",
    accountId: "a2",
    title: "Distributor visit — credit terms & competitor",
    channel: "In-Person",
    language: "Hindi",
    date: "2026-06-09T11:00:00",
    durationMin: 38,
    rep: "Vikram Reddy",
    transcript: [
      {
        speaker: "Vikram (Rep)",
        side: "rep",
        text: "Sharma ji namaste, chai ho jaaye phir baat karte hain. Pichli baar aapne 45-day credit ki baat ki thi.",
        t: 0,
      },
      {
        speaker: "Sharma ji (Distributor)",
        side: "prospect",
        text: "Haan dekho beta, 30 din mein payment cycle manage karna mushkil hai. Patanjali wale humein 60 days de rahe hain.",
        t: 18,
        drives: ["objections", "competitors", "bant.budget"],
      },
      {
        speaker: "Vikram (Rep)",
        side: "rep",
        text: "Samajh raha hoon. Main 45 days approve karwa sakta hoon agar aap monthly minimum 200 cartons commit karein.",
        t: 40,
        drives: ["nextSteps", "pricingDiscussed"],
      },
      {
        speaker: "Sharma ji (Distributor)",
        side: "prospect",
        text: "200 thoda zyada hai. But agar aap diwali ke time extra margin do toh main beta Ramesh ko bol dunga, wahi orders dekhta hai ab.",
        t: 62,
        drives: ["orgSignals", "bant.authority"],
      },
      {
        speaker: "Vikram (Rep)",
        side: "rep",
        text: "Ramesh ji se milwa dijiye, main directly unke saath ordering set kar dunga. Festival margin pe main HQ se baat karta hoon.",
        t: 85,
      },
      {
        speaker: "Sharma ji (Distributor)",
        side: "prospect",
        text: "Theek hai. Tum log service acchi dete ho, isliye main tumhare saath hoon. Bas credit aur margin theek rakho.",
        t: 105,
        drives: ["relationshipSignals", "sentiment"],
      },
    ],
    extracted: {
      stageSignal: "Negotiation",
      nextSteps: [
        "Get 45-day credit approved from HQ",
        "Confirm festival (Diwali) margin bump",
        "Get introduced to Ramesh (son, now handles ordering)",
      ],
      objections: [
        "30-day credit too tight",
        "Competitor offering 60-day terms",
      ],
      competitors: ["Patanjali Distribution"],
      pricingDiscussed: "45-day credit vs 200 carton/month minimum; festival margin ask",
      sentiment: "Positive",
      bant: {
        budget: "Cashflow-sensitive; credit terms are the real lever",
        authority: "Decision shifting from Sharma ji to son Ramesh (ordering)",
        need: "Better credit + festival margins to stay loyal",
        timeline: "Wants resolution before Diwali stocking",
      },
      orgSignals: [
        "Succession in progress: son Ramesh now controls ordering",
        "Sharma ji = relationship owner, Ramesh = emerging decision maker",
      ],
      relationshipSignals: [
        "High loyalty driven by service quality ('tumhare saath hoon')",
        "Face-to-face chai ritual — deep personal trust",
      ],
    },
    crmPush: {
      target: "Salesforce",
      payload: {
        account: "Annapurna FMCG Distribution",
        dealStage: "Negotiation",
        newContact: { name: "Ramesh Sharma", role: "Decision Maker (emerging)" },
        nextActivity: {
          type: "Approval",
          subject: "45-day credit + Diwali margin",
        },
        riskFlag: "Competitor: Patanjali (60-day credit)",
      },
    },
  },
  {
    id: "c3",
    accountId: "a3",
    title: "Discovery call — US SMB, security concerns",
    channel: "Video Call",
    language: "English",
    date: "2026-06-10T20:30:00",
    durationMin: 27,
    rep: "Sara Williams",
    transcript: [
      {
        speaker: "Sara (Rep)",
        side: "rep",
        text: "Thanks for hopping on, Mike. You mentioned your team is drowning in manual CRM updates?",
        t: 0,
      },
      {
        speaker: "Mike Donovan",
        side: "prospect",
        text: "Yeah, my reps spend a quarter of their week just logging calls. But before we go deep — where is the data stored? We're SOC 2 sensitive.",
        t: 14,
        drives: ["objections", "bant.need"],
      },
      {
        speaker: "Sara (Rep)",
        side: "rep",
        text: "Totally fair. We're SOC 2 Type II, data residency in US, and recordings are encrypted at rest. I'll send the security packet.",
        t: 33,
        drives: ["nextSteps"],
      },
      {
        speaker: "Mike Donovan",
        side: "prospect",
        text: "Good. I can approve up to $25k myself without going to the board. If it's more, that's a Q4 budget conversation.",
        t: 50,
        drives: ["orgSignals", "bant.authority", "bant.budget", "bant.timeline"],
      },
      {
        speaker: "Sara (Rep)",
        side: "rep",
        text: "Understood. For a team your size we'd land comfortably under that. Are you also evaluating Gong?",
        t: 66,
      },
      {
        speaker: "Mike Donovan",
        side: "prospect",
        text: "We looked at Gong but it's overkill and pricey for 12 reps. We mostly need the field + phone capture, not the analytics suite.",
        t: 80,
        drives: ["competitors", "sentiment"],
      },
    ],
    extracted: {
      stageSignal: "Qualified",
      nextSteps: [
        "Send SOC 2 + security packet",
        "Scope pricing under $25k self-approval threshold",
        "Position vs Gong on field/phone capture",
      ],
      objections: ["Security/SOC 2 due diligence required"],
      competitors: ["Gong"],
      pricingDiscussed: "Self-approval ceiling $25k; above = Q4 board cycle",
      sentiment: "Positive",
      bant: {
        budget: "$25k self-approval, more needs board (Q4)",
        authority: "Mike is economic buyer up to $25k",
        need: "Field + phone capture without heavy analytics overhead",
        timeline: "Now if under $25k; else Q4",
      },
      orgSignals: [
        "Mike = economic buyer (approves ≤ $25k solo)",
        "Board involved only above threshold",
      ],
      relationshipSignals: [
        "Pragmatic, ROI-driven tone",
        "Trusts vendor enough to share approval limits openly",
      ],
    },
    crmPush: {
      target: "HubSpot",
      payload: {
        account: "CloudLedger Inc",
        dealStage: "Qualified",
        nextActivity: { type: "Email", subject: "Send SOC 2 security packet" },
        contactUpdate: { name: "Mike Donovan", role: "Decision Maker" },
        riskFlag: "Competitor: Gong (evaluating)",
      },
    },
  },
  {
    id: "c4",
    accountId: "a1",
    title: "WhatsApp voice note — feature question",
    channel: "WhatsApp Voice Note",
    language: "Hinglish",
    date: "2026-06-06T09:12:00",
    durationMin: 2,
    rep: "Aarav Mehta",
    transcript: [
      {
        speaker: "Rahul Verma",
        side: "prospect",
        text: "Aarav, quick question — does your tool capture WhatsApp calls also? Kyunki humara 70% sales WhatsApp pe hi hota hai. Agar wo capture hota hai toh team buy-in easy ho jayega.",
        t: 0,
        drives: ["bant.need", "nextSteps"],
      },
    ],
    extracted: {
      stageSignal: "Demo",
      nextSteps: ["Confirm WhatsApp call capture in demo", "Loop in rep team for buy-in"],
      objections: [],
      competitors: [],
      pricingDiscussed: "—",
      sentiment: "Positive",
      bant: {
        budget: "—",
        authority: "Rahul driving internal buy-in",
        need: "WhatsApp call capture is the deciding capability (70% of selling)",
        timeline: "—",
      },
      orgSignals: ["Rahul actively building internal champion coalition"],
      relationshipSignals: ["Proactively reaching out via voice note → high engagement"],
    },
    crmPush: {
      target: "Zoho",
      payload: {
        account: "Nexus Retail Cloud",
        dealStage: "Demo",
        note: "Key need: WhatsApp call capture (70% of their selling).",
      },
    },
  },
  {
    id: "c5",
    accountId: "a4",
    title: "Pharma distributor — handover context call",
    channel: "Phone Call",
    language: "Hinglish",
    date: "2026-06-08T16:45:00",
    durationMin: 19,
    rep: "Priya Nair",
    transcript: [
      {
        speaker: "Priya (Rep)",
        side: "rep",
        text: "Dr. Khanna, main Priya — Rohan ab is region pe nahi hain, toh aage main aapke saath kaam karungi.",
        t: 0,
      },
      {
        speaker: "Dr. Khanna",
        side: "prospect",
        text: "Oh, Rohan toh bahut helpful tha. Dekhiye, humara main issue cold-chain stock ka tha — wo abhi tak resolve nahi hua.",
        t: 16,
        drives: ["objections", "relationshipSignals"],
      },
      {
        speaker: "Priya (Rep)",
        side: "rep",
        text: "Bilkul, mujhe pata hai. Rohan ke notes mein tha ki aap cold-chain SLA chahte hain. Main wo proposal aaj hi bhejti hoon.",
        t: 34,
        drives: ["nextSteps"],
      },
      {
        speaker: "Dr. Khanna",
        side: "prospect",
        text: "Achha, aapko pata hai? Good. Tab toh theek hai. Aur payment terms wahi rahenge na, 30 days?",
        t: 50,
        drives: ["sentiment", "bant.budget"],
      },
    ],
    extracted: {
      stageSignal: "Proposal",
      nextSteps: ["Send cold-chain SLA proposal today", "Confirm 30-day payment terms"],
      objections: ["Unresolved cold-chain stock SLA"],
      competitors: [],
      pricingDiscussed: "30-day payment terms to be honored post-handover",
      sentiment: "Mixed",
      bant: {
        budget: "30-day terms",
        authority: "Dr. Khanna = decision maker",
        need: "Cold-chain SLA is the blocker to close",
        timeline: "Wants resolution quickly",
      },
      orgSignals: ["Single decision maker (Dr. Khanna)"],
      relationshipSignals: [
        "Relationship was rep-dependent (strong with Rohan)",
        "Warm recovery: new rep referencing prior context preserved trust",
      ],
    },
    crmPush: {
      target: "Salesforce",
      payload: {
        account: "MediStock Pharma Distribution",
        dealStage: "Proposal",
        handover: { from: "Rohan Gupta", to: "Priya Nair" },
        nextActivity: { type: "Task", subject: "Send cold-chain SLA proposal" },
      },
    },
  },
];

export const accounts: Account[] = [
  {
    id: "a1",
    name: "Nexus Retail Cloud",
    segment: "B2B SaaS",
    industry: "Retail SaaS",
    region: "Bengaluru, IN",
    logoColor: "#6d5efc",
    initials: "NR",
    dealStage: "Negotiation",
    dealValue: 1200000,
    currency: "INR",
    probability: 65,
    relationshipScore: 78,
    owner: "Aarav Mehta",
    lastTouch: "2026-06-11T15:20:00",
    contacts: [
      {
        id: "ct1",
        name: "Rahul Verma",
        title: "Head of Sales Ops",
        role: "Champion",
        temperature: "Warm",
        rapport: 82,
        notes: "Internal champion, drives buy-in but not the signer.",
        signals: [
          "Remembered personal context (daughter's school)",
          "Reaches out proactively via WhatsApp voice notes",
        ],
      },
      {
        id: "ct2",
        name: "Anjali Desai",
        title: "VP Sales",
        role: "Decision Maker",
        temperature: "Cold",
        rapport: 24,
        notes: "Economic buyer — approves deals above ₹8L. Not yet engaged.",
        signals: ["Mentioned 3x as the final approver", "No direct touchpoint yet"],
      },
      {
        id: "ct3",
        name: "Karthik Rao",
        title: "Sales Rep",
        role: "End User",
        temperature: "Warm",
        rapport: 70,
        reportsTo: "ct1",
        notes: "Will be a daily user; cares about WhatsApp capture.",
        signals: ["Asked about Hinglish transcription accuracy"],
      },
    ],
    blockers: [
      {
        id: "b1",
        type: "Pricing",
        severity: "High",
        summary: "Per-seat price seen as ~30% above Zoho's quote.",
        suggestedAction: "Send ROI one-pager reframing on call-intelligence value.",
        raisedOn: "2026-06-11",
      },
      {
        id: "b2",
        type: "Internal Approval",
        severity: "High",
        summary: "Economic buyer (Anjali, VP Sales) not yet engaged.",
        suggestedAction: "Request joint call with Anjali via Rahul next week.",
        raisedOn: "2026-06-11",
      },
    ],
    conversationIds: ["c1", "c4"],
  },
  {
    id: "a2",
    name: "Annapurna FMCG Distribution",
    segment: "Field Sales",
    industry: "FMCG Distribution",
    region: "Kanpur, IN",
    logoColor: "#f59e0b",
    initials: "AF",
    dealStage: "Negotiation",
    dealValue: 850000,
    currency: "INR",
    probability: 55,
    relationshipScore: 84,
    owner: "Vikram Reddy",
    lastTouch: "2026-06-09T11:00:00",
    contacts: [
      {
        id: "ct4",
        name: "Sharma ji",
        title: "Distributor (Owner)",
        role: "Champion",
        temperature: "Hot",
        rapport: 90,
        notes: "Loyal due to service quality. Relationship owner.",
        signals: ["'Tumhare saath hoon' loyalty cue", "Chai-table trust ritual"],
      },
      {
        id: "ct5",
        name: "Ramesh Sharma",
        title: "Son / Ordering Lead",
        role: "Decision Maker",
        temperature: "Cool",
        rapport: 40,
        reportsTo: "ct4",
        notes: "Now controls ordering — succession in progress.",
        signals: ["Father deferring order decisions to him", "Not yet met directly"],
      },
    ],
    blockers: [
      {
        id: "b3",
        type: "Competitor",
        severity: "High",
        summary: "Patanjali offering 60-day credit vs our 30.",
        suggestedAction: "Approve 45-day credit tied to 200 carton/month commit.",
        raisedOn: "2026-06-09",
      },
      {
        id: "b4",
        type: "Trust",
        severity: "Medium",
        summary: "Relationship is with father; son (real buyer) not engaged.",
        suggestedAction: "Get introduced to Ramesh, build direct rapport.",
        raisedOn: "2026-06-09",
      },
    ],
    conversationIds: ["c2"],
  },
  {
    id: "a3",
    name: "CloudLedger Inc",
    segment: "B2B SaaS",
    industry: "Fintech SaaS",
    region: "Austin, US",
    logoColor: "#00d3a7",
    initials: "CL",
    dealStage: "Qualified",
    dealValue: 22000,
    currency: "USD",
    probability: 45,
    relationshipScore: 62,
    owner: "Sara Williams",
    lastTouch: "2026-06-10T20:30:00",
    contacts: [
      {
        id: "ct6",
        name: "Mike Donovan",
        title: "VP Revenue",
        role: "Decision Maker",
        temperature: "Warm",
        rapport: 68,
        notes: "Economic buyer up to $25k. Pragmatic.",
        signals: ["Shared approval limit openly", "ROI-driven"],
      },
      {
        id: "ct7",
        name: "Board",
        title: "Budget Committee",
        role: "Gatekeeper",
        temperature: "Cold",
        rapport: 10,
        notes: "Only involved above $25k (Q4 cycle).",
        signals: ["Q4 budget gate"],
      },
    ],
    blockers: [
      {
        id: "b5",
        type: "Technical",
        severity: "Medium",
        summary: "SOC 2 / data residency due diligence required.",
        suggestedAction: "Send SOC 2 Type II packet + US residency confirmation.",
        raisedOn: "2026-06-10",
      },
    ],
    conversationIds: ["c3"],
  },
  {
    id: "a4",
    name: "MediStock Pharma Distribution",
    segment: "Field Sales",
    industry: "Pharma Distribution",
    region: "Lucknow, IN",
    logoColor: "#ef4444",
    initials: "MS",
    dealStage: "Proposal",
    dealValue: 640000,
    currency: "INR",
    probability: 50,
    relationshipScore: 58,
    owner: "Priya Nair",
    handover: {
      fromRep: "Rohan Gupta",
      toRep: "Priya Nair",
      reason: "Rohan moved off the region",
      date: "2026-06-08",
    },
    lastTouch: "2026-06-08T16:45:00",
    contacts: [
      {
        id: "ct8",
        name: "Dr. Khanna",
        title: "Distributor Principal",
        role: "Decision Maker",
        temperature: "Cool",
        rapport: 55,
        notes: "Relationship was strongly tied to previous rep (Rohan).",
        signals: ["'Rohan was very helpful' — rep-dependent loyalty", "Warmed after context recall"],
      },
    ],
    blockers: [
      {
        id: "b6",
        type: "Technical",
        severity: "High",
        summary: "Unresolved cold-chain stock SLA blocking close.",
        suggestedAction: "Send cold-chain SLA proposal today; honor 30-day terms.",
        raisedOn: "2026-06-08",
      },
      {
        id: "b7",
        type: "Trust",
        severity: "Medium",
        summary: "Account knowledge walked out with departing rep.",
        suggestedAction: "Use preserved VoiceLog history to warm the handover.",
        raisedOn: "2026-06-08",
      },
    ],
    conversationIds: ["c5"],
  },
  {
    id: "a5",
    name: "Flipkart Seller Tools",
    segment: "B2B SaaS",
    industry: "E-commerce SaaS",
    region: "Bengaluru, IN",
    logoColor: "#3b82f6",
    initials: "FS",
    dealStage: "Demo",
    dealValue: 2100000,
    currency: "INR",
    probability: 35,
    relationshipScore: 48,
    owner: "Aarav Mehta",
    lastTouch: "2026-06-05T13:00:00",
    contacts: [
      {
        id: "ct9",
        name: "Neha Kapoor",
        title: "Director, Seller Success",
        role: "Influencer",
        temperature: "Cool",
        rapport: 45,
        notes: "Interested but early; needs exec sponsor.",
        signals: ["Engaged on demo", "No budget owner identified yet"],
      },
    ],
    blockers: [
      {
        id: "b8",
        type: "Budget Cycle",
        severity: "Medium",
        summary: "No identified economic buyer / budget line yet.",
        suggestedAction: "Map org to find exec sponsor before proposal.",
        raisedOn: "2026-06-05",
      },
    ],
    conversationIds: [],
  },
  {
    id: "a6",
    name: "Bharat Agri Distributors",
    segment: "Field Sales",
    industry: "Agritech",
    region: "Nashik, IN",
    logoColor: "#22c55e",
    initials: "BA",
    dealStage: "Qualified",
    dealValue: 470000,
    currency: "INR",
    probability: 40,
    relationshipScore: 66,
    owner: "Vikram Reddy",
    lastTouch: "2026-06-04T10:30:00",
    contacts: [
      {
        id: "ct10",
        name: "Patil Saheb",
        title: "Regional Dealer",
        role: "Champion",
        temperature: "Warm",
        rapport: 72,
        notes: "Good rapport, wants offline-first app for low connectivity.",
        signals: ["Field areas have poor network", "Trusts in-person visits"],
      },
    ],
    blockers: [
      {
        id: "b9",
        type: "Technical",
        severity: "Medium",
        summary: "Needs offline-first capture for low-connectivity villages.",
        suggestedAction: "Demo offline recording + delayed sync.",
        raisedOn: "2026-06-04",
      },
    ],
    conversationIds: [],
  },
];

export function getAccount(id: string) {
  return accounts.find((a) => a.id === id);
}

export function getConversation(id: string) {
  return conversations.find((c) => c.id === id);
}

export function getConversationsForAccount(id: string) {
  return conversations.filter((c) => c.accountId === id);
}
